### ISSUE TITLE
Meta: Error States Completeness

### ISSUE THREAD

**Issue by KimiWu123** [privacy-scaling-explorations/zkevm-circuits#1523]
- [x] ErrorWriteProtection
   - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/441
- [x] ErrorInsufficientBalance
   - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/442
- [x] ErrorContractAddressCollision
   - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/443
- [x] ErrorInvalidCreationCode
   - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/434 (WIP)
   - [x] circuit #1292 (WIP)
- [x] ErrorMaxCodeSizeExceeded
   - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/445
   - [x] circuit #1545 (WIP)
- [x] ErrorReturnDataOutOfBound
   - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/446

### Gas
- [x] ErrorOutOfGasStaticMemoryExpansion
   - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/456
   - [x] circuit #1518
- [x] ErrorOutOfGasDynamicMemoryExpansion
   - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/456
   - [x] circuit #1519 
- [x] ErrorOutOfGasMemoryCopy
  - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/414
- [x] ErrorOutOfGasAccountAccess
   - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/447
   - [x] circuit #1349 (Waiting for Scroll upstream)
- [x] ErrorOutOfGasCodeStore
   - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/445
   - [x] circuit #1545 (WIP) 
- [x] ErrorOutOfGasLOG
   - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/448
- [x] ErrorOutOfGasEXP
   - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/449
- [x] ErrorOutOfGasSHA3
   - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/450
   - [x] circuit #1520 
- [x] ~~ErrorOutOfGasEXTCODECOPY~~
   - [x] ~~spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/451~~
   - [x] ~~circuit #1521~~ 
- [x] ErrorOutOfGasSLOAD
   - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/452
- [x] ErrorOutOfGasSSTORE
   - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/453
- [x] ErrorOutOfGasCREATE2
   - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/454
   - [x] circuit #1522 
- [x] ErrorGasUintOverflow
  - [x] spec https://github.com/privacy-scaling-explorations/zkevm-specs/issues/421
  - [x] circuit #1526 

### Notice
**Update https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/477 once any one of above is done.**

**Comment by KimiWu123** [comment]
Completed!!
