### ISSUE TITLE
Meta: Finish Keccak state incrementally update implementation

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#276]
This task requires:
- [x] Keccak permutation permutation circuit implementation: https://github.com/appliedzkp/zkevm-circuits/issues/273
- [ ] Padding implementation for chunk-splitted witnesses: https://github.com/appliedzkp/zkevm-circuits/issues/336
- [x] Spec and implement an sponge implementation for keccak which does not lead to variable-length circuits. https://github.com/appliedzkp/zkevm-circuits/issues/274
- [ ] Full Keccak implementation featuring padding and MAX_ROUNDS: https://github.com/appliedzkp/zkevm-circuits/issues/274 

There are also some optimizations that could be done to the actual implementations and some refactors that would benefit the simplicity and usability of the gadget/circuit.
- [x] Refactor outside-circuit arithmetic to facilitate witness computations: https://github.com/appliedzkp/zkevm-circuits/issues/218
- [x] Implement benchmarks for Keccak circuit: https://github.com/appliedzkp/zkevm-circuits/issues/168
- [x] Keccak: Refactor BlockCountAcc: https://github.com/appliedzkp/zkevm-circuits/issues/210
- [ ] Reduce IotaB9 and IotaB13 `Advice` columns required: https://github.com/appliedzkp/zkevm-circuits/issues/275
- [x] Use `AssignedCell` instead of `(Cell,F)`: https://github.com/appliedzkp/zkevm-circuits/issues/320
- [x] Fix `AssignedCell`s value unwrappings for Verifier: https://github.com/appliedzkp/zkevm-circuits/issues/344
- [ ] Perf optimisations for permutation circuit: https://github.com/appliedzkp/zkevm-circuits/issues/489

**Comment by CPerezz** [comment]
#168 Is partially solved since #273 included benchmarks for the permutation.
We now need to bench the entire circuit with padding included.

**Comment by ChihChengLiang** [comment]
close in favor of #692
