### ISSUE TITLE
State Circuit Tracker

### ISSUE THREAD

**Issue by z2trillion** [privacy-scaling-explorations/zkevm-circuits#568]
- [x] https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/558

### BinaryNumberChip for simplifying code and lowering degree
- [x] https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/550
- [x] https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/566 - fixes https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/561

### General constraints
- [x] MPT lookups for Account/AccountStorage rows  
  - https://github.com/privacy-scaling-explorations/zkevm-specs/issues/217
  - https://github.com/privacy-scaling-explorations/zkevm-specs/pull/200#issuecomment-1144667560
  - https://github.com/privacy-scaling-explorations/zkevm-specs/pull/236
- [x] add value_prev column and related constraints: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/591
- [x] ~~https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/557~~ decided not to do this.

### Implement constraints for individual RwTableTags
- [x] build_call_context_constraints
- [ ] build_account_destructed_constraints
- [x] build_account_constraints
- [x] build_tx_refund_constraints: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/591
- [x] build_tx_access_list_account_storage_constraints: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/591
- [x] build_tx_access_list_account_constraints: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/591
- [x] build_account_storage_constraints
- [x] https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/552

### Nice to haves
- [x] Think about moving Rw::TxReceipt rows to the Tx table?
