### ISSUE TITLE
Meta: Refactor circuits to get randomness via challenge API

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#659]
Depends on https://github.com/privacy-scaling-explorations/halo2/issues/90

- [x] Bytecode Circuit https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/753
- [x] Tx Circuit https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/752
- [x] Keccak Circuit https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/751
- [x] EVM Circuit https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/750
- [x] State Circuit https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/855
- [ ] MPT Circuit? 
- [x] PublicInputs Circuit? https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/854
- [x] Super Circuit https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/853
- [x] Copy Circuit https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/955
- [x] Exp Circuit https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/956

**Comment by aguzmant103** [comment]
Pending:
- Copy circuit
- 
- Root circuit?

**Comment by ChihChengLiang** [comment]
We can call this task done. We can create a new task for MPT when we reach there.
